version: "3"

services:
  ui:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - ${UI_PORT}:3000
    volumes:
    - type: bind
      source: ./src
      target: /src
    restart: always
    tty: true